name: iai
description: A private app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1  # 轮播图
  flutter_slidable: ^3.0.1  # 可滑动组件（列表项滑动）
  path_provider: ^2.0.7  # 提供应用的各种目录
  image_picker: ^1.0.4  # 从相册选择媒体文件
  photo_view: ^0.14.0  # 查看图片
  video_player: ^2.8.1  # 播放视频
  chewie: ^1.7.4  # 播放视频（在video_player的基础上进行封装）
  video_thumbnail: ^0.5.3  # 生成视频缩略图
  sqflite: ^2.0.1  # 提供sqlite数据库

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/character.png
    - assets/images/notebook.png
    - assets/images/scene.png
    - assets/images/user.png
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
